### ISSUE TITLE
30 - Frontend development - 16

### ISSUE THREAD

**Issue by Potkis** [Project-Quatum/Project-Quantum#33]
Clone web2pdfconvert
https://www.web2pdfconvert.com/

**Comment by ghost** [comment]
Clone https://github.com/Project-Quatum/url-to-pdf
Checkout a working branch
Follow the documenation in the readme.md for the nodejs environment.

**Comment by ghost** [comment]
It's good now we have the simple input and button for handling the event. 

What should we have now is : 
- When clicking the button, it sends a request to the backend and returns the pdf. It should be uncommented when the BE is ready
- A simple pdf file for now when the button is clicked, the pdf is downloaded. It's good to have the loading icon when waiting for the backend to returning the pdf file or error messages.

**Comment by pinjamikkonen** [comment]
- Maybe fuck with CSS some more
- Remove sign in option from header
